name: 'Validate env vars'
description: 'Compares .env and secret manager and posts to PR on mismatch'
inputs:
  credentials:  # id of input
    description: 'GCP credentials'
    required: true
  secrets:
    description: 'List of secrets to pull from'
    required: true
runs:
  using: "composite"
  steps:
    - name: Compare .env 
      id: secrets
      uses: sittercity/github-actions/compare-env-vars@v0.1.0-alpha.1
      with:
        credentials: ${{ inputs.credentials }}
        secrets: ${{ inputs.secrets }}

    - uses: mshick/add-pr-comment@v1
      if: ${{ steps.secrets.outputs.warning_message }}
      with:
        message: ${{ steps.secrets.outputs.warning_message }}
        repo-token: ${{ env.BUNDLER_ACCESS_TOKEN }}
